### ISSUE TITLE
heap-buffer-overflow in test set_and_clear_more_than_a_byte

### ISSUE THREAD

**Issue by riking** [toku-sa-n/set_bits#2]
https://asan.saethlin.dev/ub?crate=set_bits&version=1.1.1

Looks like these functions are more than just a little `unsafe` :)

READ of size 16 when the memory is valid for 4 bytes

```
test set_and_clear_more_than_a_byte ... =================================================================
==19687==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x502000005250 at pc 0x556b9b9da429 bp 0x7f609d4f4590 sp 0x7f609d4f4588
READ of size 16 at 0x502000005250 thread T19
    #0 0x556b9b9da428 in set_bits::bit_operation::bit_operation::_$u7b$$u7b$closure$u7d$$u7d$::h42edb14413bb30d0 /build/src/bit_operation.rs:18:17
    #1 0x556b9b9dab9b in set_bits::bit_operation::edit_bit::h0567ed78f4940ad8 /build/src/bit_operation.rs:38:9
    #2 0x556b9b9da3ea in set_bits::bit_operation::bit_operation::hd6199d06862c2aff /build/src/bit_operation.rs:21:13
    #3 0x556b9b9dbec3 in set_bits::set::hd483c4b60554e924 /build/src/lib.rs:31:5
    #4 0x556b9b72d7db in integration_test::set_and_clear_more_than_a_byte::hccd624edff5adae5 /build/tests/integration_test.rs:176:5
    #5 0x556b9b72d442 in integration_test::set_and_clear_more_than_a_byte::_$u7b$$u7b$closure$u7d$$u7d$::hbc46a3c24a7e7796 /build/tests/integration_test.rs:172:40
```
```
0x502000005254 is located 0 bytes after 4-byte region [0x502000005250,0x502000005254)
allocated by thread T19 here:
    #0 0x556b9b6f93ee in malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
    #1 0x556b9bbe643e in std::sys::unix::alloc::_$LT$impl$u20$core..alloc..global..GlobalAlloc$u20$for$u20$std..alloc..System$GT$::alloc::hbfc48fea06eea223 /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/alloc.rs:14:13
    #2 0x556b9bb6a01a in __rdl_alloc /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/alloc.rs:394:13
    #3 0x556b9b728512 in alloc::alloc::Global::alloc_impl::h75ad76ce83a45968 /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:181:73
    #4 0x556b9b729c37 in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate::hdcfdaf0a700c8cad /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:241:9
    #5 0x556b9b72d5da in alloc::boxed::Box$LT$T$GT$::new::h6e9a983e239b3fda /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:217:9
    #6 0x556b9b72d5da in integration_test::set_and_clear_more_than_a_byte::hccd624edff5adae5 /build/tests/integration_test.rs:173:26
    #7 0x556b9b72d442 in integration_test::set_and_clear_more_than_a_byte::_$u7b$$u7b$closure$u7d$$u7d$::hbc46a3c24a7e7796 /build/tests/integration_test.rs:172:40
```
```
SUMMARY: AddressSanitizer: heap-buffer-overflow /build/src/bit_operation.rs:18:17 in set_bits::bit_operation::bit_operation::_$u7b$$u7b$closure$u7d$$u7d$::h42edb14413bb30d0
Shadow bytes around the buggy address:
  0x502000004f80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000005000: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000005080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000005100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fd fd
  0x502000005180: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
=>0x502000005200: fa fa fd fd fa fa fd fd fa fa[04]fa fa fa fa fa
  0x502000005280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000005300: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000005380: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000005400: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000005480: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==19687==ABORTING
```

**Comment by toku-sa-n** [comment]
Ahhh, thanks for the report.
Actually, I've totally forgotten this crate and repository. If you're using it, could you consider using [`bit_field`](https://crates.io/crates/bit_field) and [`accessor`](https://crates.io/crates/accessor) instead? I'm planning to deprecate this crate/repo.

**Comment by riking** [comment]
That's fine with me - it was discovered to have this issue in a crater-style job where all of crates.io is tested.

**Comment by toku-sa-n** [comment]
Thanks. I'm deprecating this crate.
